//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCleaner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCCleaner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature requires administrator priviledges.
        /// </summary>
        internal static string admin_required {
            get {
                return ResourceManager.GetString("admin_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is not running with administrative privileges. Some functions may not work properly.
        /// </summary>
        internal static string administrative_privileges_warning {
            get {
                return ResourceManager.GetString("administrative_privileges_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord is not installed on this machine.
        /// </summary>
        internal static string discord_not_installed {
            get {
                return ResourceManager.GetString("discord_not_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache folder is already empty.
        /// </summary>
        internal static string empty_folder {
            get {
                return ResourceManager.GetString("empty_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  items removed.
        /// </summary>
        internal static string items_removed {
            get {
                return ResourceManager.GetString("items_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file removed.
        /// </summary>
        internal static string No_file_removed {
            get {
                return ResourceManager.GetString("No_file_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVIDIA DXCache directory not found on this machine.
        /// </summary>
        internal static string nvidia_cache_not_exist {
            get {
                return ResourceManager.GetString("nvidia_cache_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam is not installed on this machine.
        /// </summary>
        internal static string steam_not_installed {
            get {
                return ResourceManager.GetString("steam_not_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Total size: .
        /// </summary>
        internal static string TotalSize {
            get {
                return ResourceManager.GetString("TotalSize", resourceCulture);
            }
        }
    }
}
